### ISSUE TITLE
Provide an EventBusBridge

### ISSUE THREAD

**Issue by aesteve** [aesteve/vertx-mvc#35]
`@SockJS` controllers could be annotated with `@EventBusBridge` to act as an eventbus bridge for Javascript clients.

See : http://vertx.io/docs/vertx-web/java/#_sockjs_event_bus_bridge

Problem is : [the security](http://vertx.io/docs/vertx-web/java/#_securing_the_bridge) options for the bridge, which are specified in vertx-web thanks to [PermittedOptions](http://vertx.io/docs/apidocs/io/vertx/ext/web/handler/sockjs/PermittedOptions.html) for both the inbound and outbound traffic.

How to map these permitted options and address / regex matching onto an annotation ?

Probably use several annotations like : 

``` java
@SockJS("/eventbus/*")
@EventBusBridge
@InboundPermitted("echo.*")
@OutboundPermitted("*")
public class MyBridge {
}
```

**Comment by ldallen** [comment]
What you suggest is a good solution imo. 
Maybe adding some optional parameters for the Inbound/Outbound annotations would be great, in order to be able to add some required authority when it is necessary.
I don't know if it's possible, but maybe you could put the inbound/outbound permitted options into the config file, in order to avoid to have a class definition with 10 annotations...

**Comment by aesteve** [comment]
See : https://github.com/aesteve/vertx-nubes/blob/master/src/test/java/mock/controllers/sockjs/EBBridgeDefaultController.java

It should do what you need for now. It [should be tested automatically](https://github.com/aesteve/vertx-nubes/blob/master/src/test/java/integration/sockjs/TestEventBusBridge.java).

I also implemented the Inbound/Outbound permitted options but didn't write any test yet. So it's very likely to be broken... That's why I'll leave this issue opened for now :)

**Comment by ldallen** [comment]
Hi Arnaud,

Thank you for this implementation, you're very reactive! I will try it today :)

**Comment by ldallen** [comment]
Tested with a js client, it works well! :)
I even tried with Inbound/Outbound permitted options, it seems to work too! I will let you know if I face any bug or unexpected behavior.

**Comment by ldallen** [comment]
Hi it's me again !
I did face an issue when trying to declare more than one Inbound option, so I changed your code a bit to allow repeatable annotations for Inbound/Outbound. Do you want me to post the changes here ?

**Comment by aesteve** [comment]
I must have missed something obvious, it was intended to be possible.

Could you submit a Pull request please ?

**Comment by ldallen** [comment]
Pull request submitted ! :)

**Comment by aesteve** [comment]
Thanks a lot for the PR. 

Address & AddressRegex + Multiple rules are tested automatically now.

Still need to test the authority.
