### ISSUE TITLE
Error loading jaxb.index

### ISSUE THREAD

**Issue by ldallen** [aesteve/vertx-mvc#36]
Hi !

I don't know if it's just with my computer, but when I try to start the nubes tests, I got some error like this :
"mock.domains"  doesnt contain ObjectFactory.class or jaxb.index
If I comment the line which loads the domain package, I can run the tests (90/94 passed).
Is it an issue or just intelliJ ?

**Comment by aesteve** [comment]
I'll take a look this evening. It must be IntelliJ related. 

Tests are running fine with both Eclipse JUnit Runner and `gradlew`.

Not sure I'll keep the `jaxb.index` stuff, too, I'll probably just scan the `domain-package` property value and inject every class found in the JAXBContext, that would solve the problem and people using XMLMarshaller wouldn't need to define a `jaxb.index`.

I have to figure that out.

**Comment by aesteve** [comment]
I removed jaxb.index and scan the domain package manually instead. You should be able to launch unit tests now.
