### ISSUE TITLE
Maven support?

### ISSUE THREAD

**Issue by RdeWilde** [aesteve/vertx-mvc#50]
Can I use this project into my maven structure?

**Comment by aesteve** [comment]
checkout the project (git clone) then run `gradle install` and it will install the project into your local maven repo.

then in your `pom.xml`, add a dependency to : `com.github.aesteve.vertx.nubes:vertx-nubes:0.1-SNAPSHOT`

**Comment by aesteve** [comment]
As soon as I'm happy with a version, I'll publish it to maven central. But I'm still working on the project at the moment.

**Comment by RdeWilde** [comment]
Great, thanks!
