### ISSUE TITLE
Is Nubes JAX-RS/Jersey compliant?

### ISSUE THREAD

**Issue by sixman9** [aesteve/vertx-mvc#53]
Apologies if this seems like a noob question\* but, is Nubes JAX-RS-compliant implementation?

I am aware of [vertx-jersey](https://github.com/englishtown/vertx-jersey)

Cheers

\* lol!

**Comment by aesteve** [comment]
Hi and thanks for your comment :)

No it's not. It hasn't been designed to be.

You may want to have a look at [vertx jersey](https://github.com/englishtown/vertx-jersey) which is, I think, JAX-RS compliant.
