### ISSUE TITLE
No library in jcenter repository

### ISSUE THREAD

**Issue by asthanasid** [aesteve/vertx-mvc#54]
Gradle is not being able to resolve dependency 'com.github.aesteve:nubes:1.0' from jcenter.

**Comment by aesteve** [comment]
Thanks a lot, there was a problem with my bintray maven repo.

It should be fixed soon. I'll let you know as soon as it is available.

**Comment by aesteve** [comment]
I received an email from bintray. It should be [available now](https://bintray.com/aesteve/maven/nubes/view)

Thanks again for the report.
