### ISSUE TITLE
vertx 3.2.1 support

### ISSUE THREAD

**Issue by darekxan** [aesteve/vertx-mvc#58]
We are using nubes along with many other libraries that depend on vertx.

All of them depend on vertx 3.2.1, nubes just refuse to work with it. When packing to fat-jar, the version of vertx packed 3.21, because of other libraries.
I know thats due to introduction of CompositeFuture, and the real task is is to migrate to the new API.

However, this is larger task and needs to be done carefully.

Bumping however seems to be much easier and resolves classpath related problems

**Comment by aesteve** [comment]
Thanks alot for the PR.

Available in v1.2.
