### ISSUE TITLE
Do you guys support RateLimiter or something similar

### ISSUE THREAD

**Issue by manish-panwar** [aesteve/vertx-mvc#64]
Hey Guys,

I see that you have an option for Throttling in configuration but there is TODO on top of documentation. I am wondering if you support throttling out of the box?

Thanks,
Manish

**Comment by aesteve** [comment]
[Yes](https://github.com/aesteve/nubes/blob/67d1aaa6b5a27e6349aba3d5dcc447054f9c274a/src/main/java/com/github/aesteve/vertx/nubes/Config.java#L143-L151). Based on remote address though, which might or might not be what you're needing.

There's a test, too.
