### ISSUE TITLE
Start VertxNubes

### ISSUE THREAD

**Issue by FunnyDevs** [aesteve/vertx-mvc#65]
Hi! How can i start a VertxNubes???
With Vertx i create a main class and deploy a Verticle.

**Comment by aesteve** [comment]
Nubes just gives you a `Router` instance, based on the classes it will scan in your classpath.

Just create a `VertxNubes` instance, `bootstrap` it and you'll get your `Router` back (asynchronously). Use this router just the same way you're using it in a Vert.x-Web context.

https://github.com/aesteve/nubes#how-it-works

[Here](https://github.com/aesteve/nubes/blob/master/src/test/java/integration/TestVerticle.java#L43-L84) is a concrete example of usage of Nubes within a `Verticle`

**Comment by FunnyDevs** [comment]
ok, now it works!

Thanks
