### ISSUE TITLE
i love you

### ISSUE THREAD

**Issue by CHANMYUNG** [aesteve/vertx-mvc#73]

**Comment by CHANMYUNG** [comment]
I'm sorry I didn't 

Fuckin Brother did XD

**Comment by CHANMYUNG** [comment]
his github nickname is [rlatjdfo112](https://github.com/rlatjdfo112)

**Comment by CHANMYUNG** [comment]
Sorry T^T

**Comment by aesteve** [comment]
Wtf... seriously...

**Comment by CHANMYUNG** [comment]
Sorry.. I really didn't
