### ISSUE TITLE
Chinese scrambling

### ISSUE THREAD

**Issue by itxve** [aesteve/vertx-mvc#80]
How to uniformly set response.setcontenttype ("text / HTML; charset = UTF-8") for Chinese scrambling;

**Comment by aesteve** [comment]
Hi, thanks for the issue.

Note, as the disclaimer mentions, that this repository is no longer maintained and should NOT been used.

If you're looking for an "annotation layer" on top of Vert.x you should definitely have a look at [Quarkus](https://quarkus.io).

Thank you.

**Comment by itxve** [comment]
Thank you.
